// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v5.29.3
// source: gameapp.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserContext   *UserContext           `protobuf:"bytes,1,opt,name=user_context,json=userContext,proto3" json:"user_context,omitempty"`
	RequestData   string                 `protobuf:"bytes,2,opt,name=request_data,json=requestData,proto3" json:"request_data,omitempty"` // JSON格式的请求字符串
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserRequest) Reset() {
	*x = UserRequest{}
	mi := &file_gameapp_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserRequest) ProtoMessage() {}

func (x *UserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gameapp_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserRequest.ProtoReflect.Descriptor instead.
func (*UserRequest) Descriptor() ([]byte, []int) {
	return file_gameapp_proto_rawDescGZIP(), []int{0}
}

func (x *UserRequest) GetUserContext() *UserContext {
	if x != nil {
		return x.UserContext
	}
	return nil
}

func (x *UserRequest) GetRequestData() string {
	if x != nil {
		return x.RequestData
	}
	return ""
}

type UserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ResponseData  string                 `protobuf:"bytes,2,opt,name=response_data,json=responseData,proto3" json:"response_data,omitempty"` // JSON格式的响应字符串
	ErrorMessage  string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserResponse) Reset() {
	*x = UserResponse{}
	mi := &file_gameapp_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserResponse) ProtoMessage() {}

func (x *UserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gameapp_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserResponse.ProtoReflect.Descriptor instead.
func (*UserResponse) Descriptor() ([]byte, []int) {
	return file_gameapp_proto_rawDescGZIP(), []int{1}
}

func (x *UserResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UserResponse) GetResponseData() string {
	if x != nil {
		return x.ResponseData
	}
	return ""
}

func (x *UserResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type UserContext struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsGuest       bool                   `protobuf:"varint,1,opt,name=is_guest,json=isGuest,proto3" json:"is_guest,omitempty"`
	PartnerId     string                 `protobuf:"bytes,2,opt,name=partner_id,json=partnerId,proto3" json:"partner_id,omitempty"`
	UserId        string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	UserName      string                 `protobuf:"bytes,4,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	AccessToken   string                 `protobuf:"bytes,5,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	ExtraInfo     map[string]string      `protobuf:"bytes,6,rep,name=extra_info,json=extraInfo,proto3" json:"extra_info,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // 额外的用户信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserContext) Reset() {
	*x = UserContext{}
	mi := &file_gameapp_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserContext) ProtoMessage() {}

func (x *UserContext) ProtoReflect() protoreflect.Message {
	mi := &file_gameapp_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserContext.ProtoReflect.Descriptor instead.
func (*UserContext) Descriptor() ([]byte, []int) {
	return file_gameapp_proto_rawDescGZIP(), []int{2}
}

func (x *UserContext) GetIsGuest() bool {
	if x != nil {
		return x.IsGuest
	}
	return false
}

func (x *UserContext) GetPartnerId() string {
	if x != nil {
		return x.PartnerId
	}
	return ""
}

func (x *UserContext) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserContext) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *UserContext) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *UserContext) GetExtraInfo() map[string]string {
	if x != nil {
		return x.ExtraInfo
	}
	return nil
}

var File_gameapp_proto protoreflect.FileDescriptor

const file_gameapp_proto_rawDesc = "" +
	"\n" +
	"\rgameapp.proto\x12\agateway\"i\n" +
	"\vUserRequest\x127\n" +
	"\fuser_context\x18\x01 \x01(\v2\x14.gateway.UserContextR\vuserContext\x12!\n" +
	"\frequest_data\x18\x02 \x01(\tR\vrequestData\"r\n" +
	"\fUserResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\rresponse_data\x18\x02 \x01(\tR\fresponseData\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\"\xa2\x02\n" +
	"\vUserContext\x12\x19\n" +
	"\bis_guest\x18\x01 \x01(\bR\aisGuest\x12\x1d\n" +
	"\n" +
	"partner_id\x18\x02 \x01(\tR\tpartnerId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x12\x1b\n" +
	"\tuser_name\x18\x04 \x01(\tR\buserName\x12!\n" +
	"\faccess_token\x18\x05 \x01(\tR\vaccessToken\x12B\n" +
	"\n" +
	"extra_info\x18\x06 \x03(\v2#.gateway.UserContext.ExtraInfoEntryR\textraInfo\x1a<\n" +
	"\x0eExtraInfoEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x012U\n" +
	"\x0eGameAppService\x12C\n" +
	"\x12ForwardUserRequest\x12\x14.gateway.UserRequest\x1a\x15.gateway.UserResponse\"\x00B.Z,github.com/dmdq/gmb88-protos/api/proto;protob\x06proto3"

var (
	file_gameapp_proto_rawDescOnce sync.Once
	file_gameapp_proto_rawDescData []byte
)

func file_gameapp_proto_rawDescGZIP() []byte {
	file_gameapp_proto_rawDescOnce.Do(func() {
		file_gameapp_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_gameapp_proto_rawDesc), len(file_gameapp_proto_rawDesc)))
	})
	return file_gameapp_proto_rawDescData
}

var file_gameapp_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_gameapp_proto_goTypes = []any{
	(*UserRequest)(nil),  // 0: gateway.UserRequest
	(*UserResponse)(nil), // 1: gateway.UserResponse
	(*UserContext)(nil),  // 2: gateway.UserContext
	nil,                  // 3: gateway.UserContext.ExtraInfoEntry
}
var file_gameapp_proto_depIdxs = []int32{
	2, // 0: gateway.UserRequest.user_context:type_name -> gateway.UserContext
	3, // 1: gateway.UserContext.extra_info:type_name -> gateway.UserContext.ExtraInfoEntry
	0, // 2: gateway.GameAppService.ForwardUserRequest:input_type -> gateway.UserRequest
	1, // 3: gateway.GameAppService.ForwardUserRequest:output_type -> gateway.UserResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_gameapp_proto_init() }
func file_gameapp_proto_init() {
	if File_gameapp_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gameapp_proto_rawDesc), len(file_gameapp_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_gameapp_proto_goTypes,
		DependencyIndexes: file_gameapp_proto_depIdxs,
		MessageInfos:      file_gameapp_proto_msgTypes,
	}.Build()
	File_gameapp_proto = out.File
	file_gameapp_proto_goTypes = nil
	file_gameapp_proto_depIdxs = nil
}
